### PR TITLE
Solves #1039: wro4j-maven-plugin with JDK 9

### PR DESCRIPTION
**Pull request by antoinesd**
Solves #1039: wro4j-maven-plugin with JDK 9

### CODE REVIEW

**Comment by alexo** [comment]
Thanks!

**Comment by sfeigl** [comment]
Updating mockito version seems to break test cases.

Anybody able to provide a fix for this?

**Comment by sfeigl** [comment]
Mockito changed behaviour so that null does not match .any(Class.class) any more.

There seem still some bits missing.

At the momenr I am stuck with getting the Groovy part to run. The gmaven plugin seems to be dead. But there is a potential replacement.

**Comment by ppodgorsek** [comment]
Closing this pull request, as Mockito is already being used in version 3.2.4 on the master branch.

**Pull request closed without merging**
