### PR TITLE
Update to commons-io 2.11.0

### LINKED ISSUE #1136: Upgrade commons-io from 2.8.0 to 2.11.0
In our project, we're relying on the latest wro4j version 1.10.1 and commons-io:commons-io 2.8.

We've tried to upgrade commons-io in our project to the latest version, 2.11.
Yet, it seems that some implementation changes in `org.apache.commons.io.FileUtils#listFiles` (see the [Apache Commons IO Release Notes](https://commons.apache.org/proper/commons-io/changes-report.html#a2.11.0) for 2.9.0) are breaking the existing behavior of [ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator#findMatchedFiles](https://github.com/wro4j/wro4j/blob/v1.10.1/wro4j-core/src/main/java/ro/isdc/wro/model/resource/locator/wildcard/DefaultWildcardStreamLocator.java#L136):

```
private Collection<File> findMatchedFiles(final WildcardContext wildcardContext)
    throws IOException {
  validate(wildcardContext);

  // Holds a set of all files (also folders, not only resources). This is useful for wildcard expander processing.
  final Set<File> allFiles = new TreeSet<File>(ALPHABETIC_FILE_COMPARATOR);
  final IOFileFilter fileFilter = createWildcardCollectorFileFilter(wildcardContext, allFiles);
  FileUtils.listFiles(wildcardContext.getFolder(), fileFilter, getFolderFilter(wildcardContext.getWildcard()));

  triggerWildcardExpander(allFiles, wildcardContext);

  return allFiles;
}
```

With commons-io:2.11, when calling `findMatchedFiles` with a `wildcardContext` built from:
- uri: `"file:/my/project/path/target/test-classes/css/*"`
- folder: `"/my/project/path/target/test-classes/css/"`

the  method returns an empty `allFiles` Set, leading to the stack trace below:

```
java.io.IOException: No resource found for wildcard: *
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.triggerWildcardExpander(DefaultWildcardStreamLocator.java:191)
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.findMatchedFiles(DefaultWildcardStreamLocator.java:145)
	at ro.isdc.wro.model.resource.locator.wildcard.DefaultWildcardStreamLocator.locateStream(DefaultWildcardStreamLocator.java:94)
	at ro.isdc.wro.model.resource.locator.UrlUriLocator.locate(UrlUriLocator.java:81)
```
With commons-io 2.8 and the same call, the resulting `allFiles` Set is not empty. Just after the call to `FileUtils.listFiles()`, it contains the CSS file located in `/my/project/path/target/test-classes/css/myTestFile.css`.

Would you consider upgrading to commons-io:2.11?

Thanks

### PR DESCRIPTION
**Pull request by guillaume-alvarez**
Fix #1136

### CODE REVIEW

**Review by ppodgorsek — APPROVED** [review]

**Review by ppodgorsek — CHANGES_REQUESTED** [review]
The CI pipeline failed after the PR was upgraded to the latest version from `master`.
Could you fix the issues please?

**Comment by guillaume-alvarez** [comment]
> The CI pipeline failed after the PR was upgraded to the latest version from `master`. Could you fix the issues please?

I rebased on latest master and fixed the issue.

**Comment by ppodgorsek** [comment]
> > The CI pipeline failed after the PR was upgraded to the latest version from `master`. Could you fix the issues please?
> 
> I rebased on latest master and fixed the issue.

Thank you @guillaume-alvarez, I didn't have as much time as I hoped but I will definitely review it next week. Have a nice weekend! :)

**Review by ppodgorsek — CHANGES_REQUESTED** [review]
Thank you Guillaume, I finally reviewed this PR and had more time to research this issue with commons IO. It feels like those changes are related to a regression in the commons-io library: https://issues.apache.org/jira/browse/IO-754

I think we should follow the official recommendation and rely on `accept(Path path, BasicFileAttributes attributes)` instead, to keep our logic in line with how the library has evolved.

Would you mind doing those changes please?

**Comment by kevinleturc** [comment]
Hello @ppodgorsek,
Apache Commons IO has deprecated the constructors of `WildcardFileFilter` in favor of a builder pattern, see https://github.com/apache/commons-io/blob/master/src/main/java/org/apache/commons/io/filefilter/WildcardFileFilter.java#L183.
Keeping the anonymous declaration will break at future commons-io upgrade.

Do you want to keep it and change the accept method to override?

**Comment by ppodgorsek** [comment]
Hello @kevinleturc ,

That's a very good point! Thank you for the information :)
It definitely makes sense to follow their longer-term approach if the constructors have been deprecated.

**Review by ppodgorsek — APPROVED** [review]

**Comment by ppodgorsek** [comment]
A few tweaks have been made to the PR. Additionally, the builder pattern mentioned by @kevinleturc doesn't yet exist in commons-io 2.11.0, so a separate ticket (#1159) has been created to take care of this. (commons-io 2.13.0 introduces many other changes which break many tests, hence why it will be handled in a separate ticket)

**Comment by ppodgorsek** [comment]
Thanks @guillaume-alvarez for your contribution! :)

**Pull request merged**
